package com.ninni.dye_depot.registry;

import com.ninni.dye_depot.DyeDepot;
import com.ninni.dye_depot.block.*;
import net.fabricmc.fabric.api.object.builder.v1.block.FabricBlockSettings;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.DyeColor;
import net.minecraft.world.level.block.*;
import net.minecraft.world.level.block.entity.BlockEntity;
import net.minecraft.world.level.block.entity.ShulkerBoxBlockEntity;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.block.state.properties.BedPart;
import net.minecraft.world.level.material.MapColor;
import net.minecraft.world.level.material.PushReaction;

@SuppressWarnings("unused")
public class DDBlocks {

    public static final Block SCARLET_WOOL = register("scarlet_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_WOOL = register("rose_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_WOOL = register("coral_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_WOOL = register("royal_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_WOOL = register("phthalo_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_WOOL = register("slate_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_WOOL = register("olive_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_WOOL = register("golden_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_WOOL = register("beige_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_WOOL = register("teal_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_WOOL = register("turquoise_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_WOOL = register("aqua_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_WOOL = register("verdant_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_WOOL = register("forest_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_WOOL = register("ginger_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_WOOL = register("tan_wool", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_WOOL).mapColor(DDDyes.TAN.getMapColor())));

    public static final Block SCARLET_CARPET = register("scarlet_carpet", new WoolCarpetBlock(DDDyes.SCARLET.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_CARPET = register("rose_carpet", new WoolCarpetBlock(DDDyes.ROSE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_CARPET = register("coral_carpet", new WoolCarpetBlock(DDDyes.CORAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_CARPET = register("royal_carpet", new WoolCarpetBlock(DDDyes.ROYAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_CARPET = register("phthalo_carpet", new WoolCarpetBlock(DDDyes.PHTHALO.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_CARPET = register("slate_carpet", new WoolCarpetBlock(DDDyes.SLATE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_CARPET = register("olive_carpet", new WoolCarpetBlock(DDDyes.OLIVE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_CARPET = register("golden_carpet", new WoolCarpetBlock(DDDyes.GOLDEN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_CARPET = register("beige_carpet", new WoolCarpetBlock(DDDyes.BEIGE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_CARPET = register("teal_carpet", new WoolCarpetBlock(DDDyes.TEAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_CARPET = register("turquoise_carpet", new WoolCarpetBlock(DDDyes.TURQUOISE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_CARPET = register("aqua_carpet", new WoolCarpetBlock(DDDyes.AQUA.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_CARPET = register("verdant_carpet", new WoolCarpetBlock(DDDyes.VERDANT.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_CARPET = register("forest_carpet", new WoolCarpetBlock(DDDyes.FOREST.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_CARPET = register("ginger_carpet", new WoolCarpetBlock(DDDyes.GINGER.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_CARPET = register("tan_carpet", new WoolCarpetBlock(DDDyes.TAN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_CARPET).mapColor(DDDyes.TAN.getMapColor())));

    public static final Block SCARLET_TERRACOTTA = register("scarlet_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_TERRACOTTA = register("rose_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_TERRACOTTA = register("coral_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_TERRACOTTA = register("royal_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_TERRACOTTA = register("phthalo_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_TERRACOTTA = register("slate_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_TERRACOTTA = register("olive_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_TERRACOTTA = register("golden_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_TERRACOTTA = register("beige_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_TERRACOTTA = register("teal_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_TERRACOTTA = register("turquoise_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_TERRACOTTA = register("aqua_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_TERRACOTTA = register("verdant_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_TERRACOTTA = register("forest_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_TERRACOTTA = register("ginger_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_TERRACOTTA = register("tan_terracotta", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_TERRACOTTA).mapColor(DDDyes.TAN.getMapColor())));

    public static final Block SCARLET_CONCRETE = register("scarlet_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.CRIMSON_HYPHAE)));
    public static final Block ROSE_CONCRETE = register("rose_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_RED)));
    public static final Block CORAL_CONCRETE = register("coral_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.PODZOL)));
    public static final Block ROYAL_CONCRETE = register("royal_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.WARPED_HYPHAE)));
    public static final Block PHTHALO_CONCRETE = register("phthalo_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.TERRACOTTA_BLACK)));
    public static final Block SLATE_CONCRETE = register("slate_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_GRAY)));
    public static final Block OLIVE_CONCRETE = register("olive_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_BROWN)));
    public static final Block GOLDEN_CONCRETE = register("golden_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.WOOD)));
    public static final Block BEIGE_CONCRETE = register("beige_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.TERRACOTTA_WHITE)));
    public static final Block TEAL_CONCRETE = register("teal_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_GRAY)));
    public static final Block TURQUOISE_CONCRETE = register("turquoise_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.DEEPSLATE)));
    public static final Block AQUA_CONCRETE = register("aqua_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.WARPED_WART_BLOCK)));
    public static final Block VERDANT_CONCRETE = register("verdant_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.TERRACOTTA_BLACK)));
    public static final Block FOREST_CONCRETE = register("forest_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.COLOR_GREEN)));
    public static final Block GINGER_CONCRETE = register("ginger_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.NETHER)));
    public static final Block TAN_CONCRETE = register("tan_concrete", new Block(FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE).mapColor(MapColor.DIRT)));

    public static final Block SCARLET_CONCRETE_POWDER = register("scarlet_concrete_powder", new ConcretePowderBlock(SCARLET_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_CONCRETE_POWDER = register("rose_concrete_powder", new ConcretePowderBlock(ROSE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_CONCRETE_POWDER = register("coral_concrete_powder", new ConcretePowderBlock(CORAL_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_CONCRETE_POWDER = register("royal_concrete_powder", new ConcretePowderBlock(ROYAL_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_CONCRETE_POWDER = register("phthalo_concrete_powder", new ConcretePowderBlock(PHTHALO_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_CONCRETE_POWDER = register("slate_concrete_powder", new ConcretePowderBlock(SLATE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_CONCRETE_POWDER = register("olive_concrete_powder", new ConcretePowderBlock(OLIVE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_CONCRETE_POWDER = register("golden_concrete_powder", new ConcretePowderBlock(GOLDEN_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_CONCRETE_POWDER = register("beige_concrete_powder", new ConcretePowderBlock(BEIGE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_CONCRETE_POWDER = register("teal_concrete_powder", new ConcretePowderBlock(TEAL_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_CONCRETE_POWDER = register("turquoise_concrete_powder", new ConcretePowderBlock(TURQUOISE_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_CONCRETE_POWDER = register("aqua_concrete_powder", new ConcretePowderBlock(AQUA_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_CONCRETE_POWDER = register("verdant_concrete_powder", new ConcretePowderBlock(VERDANT_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_CONCRETE_POWDER = register("forest_concrete_powder", new ConcretePowderBlock(FOREST_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_CONCRETE_POWDER = register("ginger_concrete_powder", new ConcretePowderBlock(GINGER_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_CONCRETE_POWDER = register("tan_concrete_powder", new ConcretePowderBlock(TAN_CONCRETE, FabricBlockSettings.copyOf(Blocks.WHITE_CONCRETE_POWDER).mapColor(DDDyes.TAN.getMapColor())));

    public static final Block SCARLET_GLAZED_TERRACOTTA = register("scarlet_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_GLAZED_TERRACOTTA = register("rose_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_GLAZED_TERRACOTTA = register("coral_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_GLAZED_TERRACOTTA = register("royal_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_GLAZED_TERRACOTTA = register("phthalo_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_GLAZED_TERRACOTTA = register("slate_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_GLAZED_TERRACOTTA = register("olive_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_GLAZED_TERRACOTTA = register("golden_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_GLAZED_TERRACOTTA = register("beige_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_GLAZED_TERRACOTTA = register("teal_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_GLAZED_TERRACOTTA = register("turquoise_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_GLAZED_TERRACOTTA = register("aqua_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_GLAZED_TERRACOTTA = register("verdant_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_GLAZED_TERRACOTTA = register("forest_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_GLAZED_TERRACOTTA = register("ginger_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_GLAZED_TERRACOTTA = register("tan_glazed_terracotta", new GlazedTerracottaBlock(FabricBlockSettings.copyOf(Blocks.WHITE_GLAZED_TERRACOTTA).mapColor(DDDyes.TAN.getMapColor())));

    public static final Block SCARLET_STAINED_GLASS = register("scarlet_stained_glass", new StainedGlassBlock(DDDyes.SCARLET.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block ROSE_STAINED_GLASS = register("rose_stained_glass", new StainedGlassBlock(DDDyes.ROSE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block CORAL_STAINED_GLASS = register("coral_stained_glass", new StainedGlassBlock(DDDyes.CORAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block ROYAL_STAINED_GLASS = register("royal_stained_glass", new StainedGlassBlock(DDDyes.ROYAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block PHTHALO_STAINED_GLASS = register("phthalo_stained_glass", new StainedGlassBlock(DDDyes.PHTHALO.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block SLATE_STAINED_GLASS = register("slate_stained_glass", new StainedGlassBlock(DDDyes.SLATE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block OLIVE_STAINED_GLASS = register("olive_stained_glass", new StainedGlassBlock(DDDyes.OLIVE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block GOLDEN_STAINED_GLASS = register("golden_stained_glass", new StainedGlassBlock(DDDyes.GOLDEN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block BEIGE_STAINED_GLASS = register("beige_stained_glass", new StainedGlassBlock(DDDyes.BEIGE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block TEAL_STAINED_GLASS = register("teal_stained_glass", new StainedGlassBlock(DDDyes.TEAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block TURQUOISE_STAINED_GLASS = register("turquoise_stained_glass", new StainedGlassBlock(DDDyes.TURQUOISE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block AQUA_STAINED_GLASS = register("aqua_stained_glass", new StainedGlassBlock(DDDyes.AQUA.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block VERDANT_STAINED_GLASS = register("verdant_stained_glass", new StainedGlassBlock(DDDyes.VERDANT.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block FOREST_STAINED_GLASS = register("forest_stained_glass", new StainedGlassBlock(DDDyes.FOREST.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block GINGER_STAINED_GLASS = register("ginger_stained_glass", new StainedGlassBlock(DDDyes.GINGER.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));
    public static final Block TAN_STAINED_GLASS = register("tan_stained_glass", new StainedGlassBlock(DDDyes.TAN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS)));

    public static final Block SCARLET_STAINED_GLASS_PANE = register("scarlet_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.SCARLET.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block ROSE_STAINED_GLASS_PANE = register("rose_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.ROSE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block CORAL_STAINED_GLASS_PANE = register("coral_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.CORAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block ROYAL_STAINED_GLASS_PANE = register("royal_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.ROYAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block PHTHALO_STAINED_GLASS_PANE = register("phthalo_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.PHTHALO.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block SLATE_STAINED_GLASS_PANE = register("slate_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.SLATE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block OLIVE_STAINED_GLASS_PANE = register("olive_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.OLIVE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block GOLDEN_STAINED_GLASS_PANE = register("golden_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.GOLDEN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block BEIGE_STAINED_GLASS_PANE = register("beige_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.BEIGE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block TEAL_STAINED_GLASS_PANE = register("teal_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.TEAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block TURQUOISE_STAINED_GLASS_PANE = register("turquoise_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.TURQUOISE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block AQUA_STAINED_GLASS_PANE = register("aqua_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.AQUA.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block VERDANT_STAINED_GLASS_PANE = register("verdant_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.VERDANT.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block FOREST_STAINED_GLASS_PANE = register("forest_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.FOREST.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block GINGER_STAINED_GLASS_PANE = register("ginger_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.GINGER.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));
    public static final Block TAN_STAINED_GLASS_PANE = register("tan_stained_glass_pane", new StainedGlassPaneBlock(DDDyes.TAN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_STAINED_GLASS_PANE)));

    public static final Block SCARLET_SHULKER_BOX = register("scarlet_shulker_box", shulkerBox(DDDyes.SCARLET.get(), FabricBlockSettings.create().mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_SHULKER_BOX = register("rose_shulker_box", shulkerBox(DDDyes.ROSE.get(), FabricBlockSettings.create().mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_SHULKER_BOX = register("coral_shulker_box", shulkerBox(DDDyes.CORAL.get(), FabricBlockSettings.create().mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_SHULKER_BOX = register("royal_shulker_box", shulkerBox(DDDyes.ROYAL.get(), FabricBlockSettings.create().mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_SHULKER_BOX = register("phthalo_shulker_box", shulkerBox(DDDyes.PHTHALO.get(), FabricBlockSettings.create().mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_SHULKER_BOX = register("slate_shulker_box", shulkerBox(DDDyes.SLATE.get(), FabricBlockSettings.create().mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_SHULKER_BOX = register("olive_shulker_box", shulkerBox(DDDyes.OLIVE.get(), FabricBlockSettings.create().mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_SHULKER_BOX = register("golden_shulker_box", shulkerBox(DDDyes.GOLDEN.get(), FabricBlockSettings.create().mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_SHULKER_BOX = register("beige_shulker_box", shulkerBox(DDDyes.BEIGE.get(), FabricBlockSettings.create().mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_SHULKER_BOX = register("teal_shulker_box", shulkerBox(DDDyes.TEAL.get(), FabricBlockSettings.create().mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_SHULKER_BOX = register("turquoise_shulker_box", shulkerBox(DDDyes.TURQUOISE.get(), FabricBlockSettings.create().mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_SHULKER_BOX = register("aqua_shulker_box", shulkerBox(DDDyes.AQUA.get(), FabricBlockSettings.create().mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_SHULKER_BOX = register("verdant_shulker_box", shulkerBox(DDDyes.VERDANT.get(), FabricBlockSettings.create().mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_SHULKER_BOX = register("forest_shulker_box", shulkerBox(DDDyes.FOREST.get(), FabricBlockSettings.create().mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_SHULKER_BOX = register("ginger_shulker_box", shulkerBox(DDDyes.GINGER.get(), FabricBlockSettings.create().mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_SHULKER_BOX = register("tan_shulker_box", shulkerBox(DDDyes.TAN.get(), FabricBlockSettings.create().mapColor(DDDyes.TAN.getMapColor())));

    public static final Block SCARLET_CANDLE = register("scarlet_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_CANDLE = register("rose_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_CANDLE = register("coral_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_CANDLE = register("royal_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_CANDLE = register("phthalo_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_CANDLE = register("slate_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_CANDLE = register("olive_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_CANDLE = register("golden_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_CANDLE = register("beige_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_CANDLE = register("teal_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_CANDLE = register("turquoise_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_CANDLE = register("aqua_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_CANDLE = register("verdant_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_CANDLE = register("forest_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_CANDLE = register("ginger_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_CANDLE = register("tan_candle", new CandleBlock(FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE).mapColor(DDDyes.TAN.getMapColor())));

    public static final Block SCARLET_CANDLE_CAKE = register("scarlet_candle_cake", new CandleCakeBlock(SCARLET_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block ROSE_CANDLE_CAKE = register("rose_candle_cake", new CandleCakeBlock(ROSE_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block CORAL_CANDLE_CAKE = register("coral_candle_cake", new CandleCakeBlock(CORAL_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block ROYAL_CANDLE_CAKE = register("royal_candle_cake", new CandleCakeBlock(ROYAL_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block PHTHALO_CANDLE_CAKE = register("phthalo_candle_cake", new CandleCakeBlock(PHTHALO_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block SLATE_CANDLE_CAKE = register("slate_candle_cake", new CandleCakeBlock(SLATE_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block OLIVE_CANDLE_CAKE = register("olive_candle_cake", new CandleCakeBlock(OLIVE_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block GOLDEN_CANDLE_CAKE = register("golden_candle_cake", new CandleCakeBlock(GOLDEN_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block BEIGE_CANDLE_CAKE = register("beige_candle_cake", new CandleCakeBlock(BEIGE_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block TEAL_CANDLE_CAKE = register("teal_candle_cake", new CandleCakeBlock(TEAL_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block TURQUOISE_CANDLE_CAKE = register("turquoise_candle_cake", new CandleCakeBlock(TURQUOISE_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block AQUA_CANDLE_CAKE = register("aqua_candle_cake", new CandleCakeBlock(AQUA_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block VERDANT_CANDLE_CAKE = register("verdant_candle_cake", new CandleCakeBlock(VERDANT_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block FOREST_CANDLE_CAKE = register("forest_candle_cake", new CandleCakeBlock(FOREST_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block GINGER_CANDLE_CAKE = register("ginger_candle_cake", new CandleCakeBlock(GINGER_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));
    public static final Block TAN_CANDLE_CAKE = register("tan_candle_cake", new CandleCakeBlock(TAN_CANDLE, FabricBlockSettings.copyOf(Blocks.WHITE_CANDLE_CAKE)));

    public static final Block SCARLET_BANNER = register("scarlet_banner", new DDBannerBlock(DDDyes.SCARLET.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block ROSE_BANNER = register("rose_banner", new DDBannerBlock(DDDyes.ROSE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block CORAL_BANNER = register("coral_banner", new DDBannerBlock(DDDyes.CORAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block ROYAL_BANNER = register("royal_banner", new DDBannerBlock(DDDyes.ROYAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block PHTHALO_BANNER = register("phthalo_banner", new DDBannerBlock(DDDyes.PHTHALO.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block SLATE_BANNER = register("slate_banner", new DDBannerBlock(DDDyes.SLATE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block OLIVE_BANNER = register("olive_banner", new DDBannerBlock(DDDyes.OLIVE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block GOLDEN_BANNER = register("golden_banner", new DDBannerBlock(DDDyes.GOLDEN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block BEIGE_BANNER = register("beige_banner", new DDBannerBlock(DDDyes.BEIGE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block TEAL_BANNER = register("teal_banner", new DDBannerBlock(DDDyes.TEAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block TURQUOISE_BANNER = register("turquoise_banner", new DDBannerBlock(DDDyes.TURQUOISE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block AQUA_BANNER = register("aqua_banner", new DDBannerBlock(DDDyes.AQUA.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block VERDANT_BANNER = register("verdant_banner", new DDBannerBlock(DDDyes.VERDANT.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block FOREST_BANNER = register("forest_banner", new DDBannerBlock(DDDyes.FOREST.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block GINGER_BANNER = register("ginger_banner", new DDBannerBlock(DDDyes.GINGER.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block TAN_BANNER = register("tan_banner", new DDBannerBlock(DDDyes.TAN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_BANNER)));
    public static final Block SCARLET_WALL_BANNER = register("scarlet_wall_banner", new DDWallBannerBlock(DDDyes.SCARLET.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(SCARLET_BANNER)));
    public static final Block ROSE_WALL_BANNER = register("rose_wall_banner", new DDWallBannerBlock(DDDyes.ROSE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(ROSE_BANNER)));
    public static final Block CORAL_WALL_BANNER = register("coral_wall_banner", new DDWallBannerBlock(DDDyes.CORAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(CORAL_BANNER)));
    public static final Block ROYAL_WALL_BANNER = register("royal_wall_banner", new DDWallBannerBlock(DDDyes.ROYAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(ROYAL_BANNER)));
    public static final Block PHTHALO_WALL_BANNER = register("phthalo_wall_banner", new DDWallBannerBlock(DDDyes.PHTHALO.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(PHTHALO_BANNER)));
    public static final Block SLATE_WALL_BANNER = register("slate_wall_banner", new DDWallBannerBlock(DDDyes.SLATE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(SLATE_BANNER)));
    public static final Block OLIVE_WALL_BANNER = register("olive_wall_banner", new DDWallBannerBlock(DDDyes.OLIVE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(OLIVE_BANNER)));
    public static final Block GOLDEN_WALL_BANNER = register("golden_wall_banner", new DDWallBannerBlock(DDDyes.GOLDEN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(GOLDEN_BANNER)));
    public static final Block BEIGE_WALL_BANNER = register("beige_wall_banner", new DDWallBannerBlock(DDDyes.BEIGE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(BEIGE_BANNER)));
    public static final Block TEAL_WALL_BANNER = register("teal_wall_banner", new DDWallBannerBlock(DDDyes.TEAL.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(TEAL_BANNER)));
    public static final Block TURQUOISE_WALL_BANNER = register("turquoise_wall_banner", new DDWallBannerBlock(DDDyes.TURQUOISE.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(TURQUOISE_BANNER)));
    public static final Block AQUA_WALL_BANNER = register("aqua_wall_banner", new DDWallBannerBlock(DDDyes.AQUA.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(AQUA_BANNER)));
    public static final Block VERDANT_WALL_BANNER = register("verdant_wall_banner", new DDWallBannerBlock(DDDyes.VERDANT.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(VERDANT_BANNER)));
    public static final Block FOREST_WALL_BANNER = register("forest_wall_banner", new DDWallBannerBlock(DDDyes.FOREST.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(FOREST_BANNER)));
    public static final Block GINGER_WALL_BANNER = register("ginger_wall_banner", new DDWallBannerBlock(DDDyes.GINGER.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(GINGER_BANNER)));
    public static final Block TAN_WALL_BANNER = register("tan_wall_banner", new DDWallBannerBlock(DDDyes.TAN.get(), FabricBlockSettings.copyOf(Blocks.WHITE_WALL_BANNER).dropsLike(TAN_BANNER)));

    public static final Block SCARLET_BED = register("scarlet_bed", bed(DDDyes.SCARLET.get()));
    public static final Block ROSE_BED = register("rose_bed", bed(DDDyes.ROSE.get()));
    public static final Block CORAL_BED = register("coral_bed", bed(DDDyes.CORAL.get()));
    public static final Block ROYAL_BED = register("royal_bed", bed(DDDyes.ROYAL.get()));
    public static final Block PHTHALO_BED = register("phthalo_bed", bed(DDDyes.PHTHALO.get()));
    public static final Block SLATE_BED = register("slate_bed", bed(DDDyes.SLATE.get()));
    public static final Block OLIVE_BED = register("olive_bed", bed(DDDyes.OLIVE.get()));
    public static final Block GOLDEN_BED = register("golden_bed", bed(DDDyes.GOLDEN.get()));
    public static final Block BEIGE_BED = register("beige_bed", bed(DDDyes.BEIGE.get()));
    public static final Block TEAL_BED = register("teal_bed", bed(DDDyes.TEAL.get()));
    public static final Block TURQUOISE_BED = register("turquoise_bed", bed(DDDyes.TURQUOISE.get()));
    public static final Block AQUA_BED = register("aqua_bed", bed(DDDyes.AQUA.get()));
    public static final Block VERDANT_BED = register("verdant_bed", bed(DDDyes.VERDANT.get()));
    public static final Block FOREST_BED = register("forest_bed", bed(DDDyes.FOREST.get()));
    public static final Block GINGER_BED = register("ginger_bed", bed(DDDyes.GINGER.get()));
    public static final Block TAN_BED = register("tan_bed", bed(DDDyes.TAN.get()));

    public static final Block SCARLET_DYE_BASKET = register("scarlet_dye_basket", new DyeBasketBlock(DDDyes.SCARLET.get(), FabricBlockSettings.create().strength(0.8f).sound(SoundType.WOOL).ignitedByLava().mapColor(DDDyes.SCARLET.getMapColor())));
    public static final Block ROSE_DYE_BASKET = register("rose_dye_basket", new DyeBasketBlock(DDDyes.ROSE.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.ROSE.getMapColor())));
    public static final Block CORAL_DYE_BASKET = register("coral_dye_basket", new DyeBasketBlock(DDDyes.CORAL.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.CORAL.getMapColor())));
    public static final Block ROYAL_DYE_BASKET = register("royal_dye_basket", new DyeBasketBlock(DDDyes.ROYAL.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.ROYAL.getMapColor())));
    public static final Block PHTHALO_DYE_BASKET = register("phthalo_dye_basket", new DyeBasketBlock(DDDyes.PHTHALO.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.PHTHALO.getMapColor())));
    public static final Block SLATE_DYE_BASKET = register("slate_dye_basket", new DyeBasketBlock(DDDyes.SLATE.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.SLATE.getMapColor())));
    public static final Block OLIVE_DYE_BASKET = register("olive_dye_basket", new DyeBasketBlock(DDDyes.OLIVE.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.OLIVE.getMapColor())));
    public static final Block GOLDEN_DYE_BASKET = register("golden_dye_basket", new DyeBasketBlock(DDDyes.GOLDEN.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.GOLDEN.getMapColor())));
    public static final Block BEIGE_DYE_BASKET = register("beige_dye_basket", new DyeBasketBlock(DDDyes.BEIGE.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.BEIGE.getMapColor())));
    public static final Block TEAL_DYE_BASKET = register("teal_dye_basket", new DyeBasketBlock(DDDyes.TEAL.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.TEAL.getMapColor())));
    public static final Block TURQUOISE_DYE_BASKET = register("turquoise_dye_basket", new DyeBasketBlock(DDDyes.TURQUOISE.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.TURQUOISE.getMapColor())));
    public static final Block AQUA_DYE_BASKET = register("aqua_dye_basket", new DyeBasketBlock(DDDyes.AQUA.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.AQUA.getMapColor())));
    public static final Block VERDANT_DYE_BASKET = register("verdant_dye_basket", new DyeBasketBlock(DDDyes.VERDANT.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.VERDANT.getMapColor())));
    public static final Block FOREST_DYE_BASKET = register("forest_dye_basket", new DyeBasketBlock(DDDyes.FOREST.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.FOREST.getMapColor())));
    public static final Block GINGER_DYE_BASKET = register("ginger_dye_basket", new DyeBasketBlock(DDDyes.GINGER.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.GINGER.getMapColor())));
    public static final Block TAN_DYE_BASKET = register("tan_dye_basket", new DyeBasketBlock(DDDyes.TAN.get(), FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DDDyes.TAN.getMapColor())));
    public static final Block WHITE_DYE_BASKET = register("white_dye_basket", new DyeBasketBlock(DyeColor.WHITE, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.WHITE.getMapColor())));
    public static final Block LIGHT_GRAY_DYE_BASKET = register("light_gray_dye_basket", new DyeBasketBlock(DyeColor.LIGHT_GRAY, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.LIGHT_GRAY.getMapColor())));
    public static final Block GRAY_DYE_BASKET = register("gray_dye_basket", new DyeBasketBlock(DyeColor.GRAY, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.GRAY.getMapColor())));
    public static final Block BLACK_DYE_BASKET = register("black_dye_basket", new DyeBasketBlock(DyeColor.BLACK, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.BLACK.getMapColor())));
    public static final Block BROWN_DYE_BASKET = register("brown_dye_basket", new DyeBasketBlock(DyeColor.BROWN, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.BROWN.getMapColor())));
    public static final Block RED_DYE_BASKET = register("red_dye_basket", new DyeBasketBlock(DyeColor.RED, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.RED.getMapColor())));
    public static final Block ORANGE_DYE_BASKET = register("orange_dye_basket", new DyeBasketBlock(DyeColor.ORANGE, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.ORANGE.getMapColor())));
    public static final Block YELLOW_DYE_BASKET = register("yellow_dye_basket", new DyeBasketBlock(DyeColor.YELLOW, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.YELLOW.getMapColor())));
    public static final Block LIME_DYE_BASKET = register("lime_dye_basket", new DyeBasketBlock(DyeColor.LIME, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.LIME.getMapColor())));
    public static final Block CYAN_DYE_BASKET = register("cyan_dye_basket", new DyeBasketBlock(DyeColor.CYAN, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.CYAN.getMapColor())));
    public static final Block GREEN_DYE_BASKET = register("green_dye_basket", new DyeBasketBlock(DyeColor.GREEN, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.GREEN.getMapColor())));
    public static final Block BLUE_DYE_BASKET = register("blue_dye_basket", new DyeBasketBlock(DyeColor.BLUE, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.BLUE.getMapColor())));
    public static final Block LIGHT_BLUE_DYE_BASKET = register("light_blue_dye_basket", new DyeBasketBlock(DyeColor.LIGHT_BLUE, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.LIGHT_BLUE.getMapColor())));
    public static final Block PURPLE_DYE_BASKET = register("purple_dye_basket", new DyeBasketBlock(DyeColor.PURPLE, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.PURPLE.getMapColor())));
    public static final Block MAGENTA_DYE_BASKET = register("magenta_dye_basket", new DyeBasketBlock(DyeColor.MAGENTA, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.MAGENTA.getMapColor())));
    public static final Block PINK_DYE_BASKET = register("pink_dye_basket", new DyeBasketBlock(DyeColor.PINK, FabricBlockSettings.copyOf(SCARLET_DYE_BASKET).mapColor(DyeColor.PINK.getMapColor())));

    private static DDBedBlock bed(DyeColor dyeColor) {
        return new DDBedBlock(dyeColor, BlockBehaviour.Properties.of().mapColor((blockState) -> blockState.getValue(DDBedBlock.PART) == BedPart.FOOT ? dyeColor.getMapColor() : MapColor.WOOL).sound(SoundType.WOOD).strength(0.2F).noOcclusion().ignitedByLava().pushReaction(PushReaction.DESTROY));
    }

    private static DDShulkerBoxBlock shulkerBox(DyeColor dyeColor, BlockBehaviour.Properties properties) {
        BlockBehaviour.StatePredicate statePredicate = (blockState, blockGetter, blockPos) -> {
            BlockEntity blockEntity = blockGetter.getBlockEntity(blockPos);
            if (blockEntity instanceof ShulkerBoxBlockEntity shulkerBoxBlockEntity) return shulkerBoxBlockEntity.isClosed();
            else return true;
        };
        return new DDShulkerBoxBlock(dyeColor, properties.forceSolidOn().strength(2.0F).dynamicShape().noOcclusion().isSuffocating(statePredicate).isViewBlocking(statePredicate).pushReaction(PushReaction.DESTROY).isRedstoneConductor(Blocks::always));
    }
    
    private static Block register(String id, Block block) {
        return Registry.register(BuiltInRegistries.BLOCK, new ResourceLocation(DyeDepot.MOD_ID, id), block);
    }
}
