package com.ninni.dye_depot.registry;

import com.ninni.dye_depot.DyeDepot;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.*;

public class DDItems {

    public static final Item SCARLET_DYE = register("scarlet_dye", new DyeItem(DDDyes.SCARLET.get(), new Item.Properties()));
    public static final Item ROSE_DYE = register("rose_dye", new DyeItem(DDDyes.ROSE.get(), new Item.Properties()));
    public static final Item CORAL_DYE = register("coral_dye", new DyeItem(DDDyes.CORAL.get(), new Item.Properties()));
    public static final Item ROYAL_DYE = register("royal_dye", new DyeItem(DDDyes.ROYAL.get(), new Item.Properties()));
    public static final Item PHTHALO_DYE = register("phthalo_dye", new DyeItem(DDDyes.PHTHALO.get(), new Item.Properties()));
    public static final Item SLATE_DYE = register("slate_dye", new DyeItem(DDDyes.SLATE.get(), new Item.Properties()));
    public static final Item OLIVE_DYE = register("olive_dye", new DyeItem(DDDyes.OLIVE.get(), new Item.Properties()));
    public static final Item GOLDEN_DYE = register("golden_dye", new DyeItem(DDDyes.GOLDEN.get(), new Item.Properties()));
    public static final Item BEIGE_DYE = register("beige_dye", new DyeItem(DDDyes.BEIGE.get(), new Item.Properties()));
    public static final Item TEAL_DYE = register("teal_dye", new DyeItem(DDDyes.TEAL.get(), new Item.Properties()));
    public static final Item TURQUOISE_DYE = register("turquoise_dye", new DyeItem(DDDyes.TURQUOISE.get(), new Item.Properties()));
    public static final Item AQUA_DYE = register("aqua_dye", new DyeItem(DDDyes.AQUA.get(), new Item.Properties()));
    public static final Item VERDANT_DYE = register("verdant_dye", new DyeItem(DDDyes.VERDANT.get(), new Item.Properties()));
    public static final Item FOREST_DYE = register("forest_dye", new DyeItem(DDDyes.FOREST.get(), new Item.Properties()));
    public static final Item GINGER_DYE = register("ginger_dye", new DyeItem(DDDyes.GINGER.get(), new Item.Properties()));
    public static final Item TAN_DYE = register("tan_dye", new DyeItem(DDDyes.TAN.get(), new Item.Properties()));

    public static final Item SCARLET_WOOL = register("scarlet_wool", new BlockItem(DDBlocks.SCARLET_WOOL, new Item.Properties()));
    public static final Item ROSE_WOOL = register("rose_wool", new BlockItem(DDBlocks.ROSE_WOOL, new Item.Properties()));
    public static final Item CORAL_WOOL = register("coral_wool", new BlockItem(DDBlocks.CORAL_WOOL, new Item.Properties()));
    public static final Item ROYAL_WOOL = register("royal_wool", new BlockItem(DDBlocks.ROYAL_WOOL, new Item.Properties()));
    public static final Item PHTHALO_WOOL = register("phthalo_wool", new BlockItem(DDBlocks.PHTHALO_WOOL, new Item.Properties()));
    public static final Item SLATE_WOOL = register("slate_wool", new BlockItem(DDBlocks.SLATE_WOOL, new Item.Properties()));
    public static final Item OLIVE_WOOL = register("olive_wool", new BlockItem(DDBlocks.OLIVE_WOOL, new Item.Properties()));
    public static final Item GOLDEN_WOOL = register("golden_wool", new BlockItem(DDBlocks.GOLDEN_WOOL, new Item.Properties()));
    public static final Item BEIGE_WOOL = register("beige_wool", new BlockItem(DDBlocks.BEIGE_WOOL, new Item.Properties()));
    public static final Item TEAL_WOOL = register("teal_wool", new BlockItem(DDBlocks.TEAL_WOOL, new Item.Properties()));
    public static final Item TURQUOISE_WOOL = register("turquoise_wool", new BlockItem(DDBlocks.TURQUOISE_WOOL, new Item.Properties()));
    public static final Item AQUA_WOOL = register("aqua_wool", new BlockItem(DDBlocks.AQUA_WOOL, new Item.Properties()));
    public static final Item VERDANT_WOOL = register("verdant_wool", new BlockItem(DDBlocks.VERDANT_WOOL, new Item.Properties()));
    public static final Item FOREST_WOOL = register("forest_wool", new BlockItem(DDBlocks.FOREST_WOOL, new Item.Properties()));
    public static final Item GINGER_WOOL = register("ginger_wool", new BlockItem(DDBlocks.GINGER_WOOL, new Item.Properties()));
    public static final Item TAN_WOOL = register("tan_wool", new BlockItem(DDBlocks.TAN_WOOL, new Item.Properties()));

    public static final Item SCARLET_CARPET = register("scarlet_carpet", new BlockItem(DDBlocks.SCARLET_CARPET, new Item.Properties()));
    public static final Item ROSE_CARPET = register("rose_carpet", new BlockItem(DDBlocks.ROSE_CARPET, new Item.Properties()));
    public static final Item CORAL_CARPET = register("coral_carpet", new BlockItem(DDBlocks.CORAL_CARPET, new Item.Properties()));
    public static final Item ROYAL_CARPET = register("royal_carpet", new BlockItem(DDBlocks.ROYAL_CARPET, new Item.Properties()));
    public static final Item PHTHALO_CARPET = register("phthalo_carpet", new BlockItem(DDBlocks.PHTHALO_CARPET, new Item.Properties()));
    public static final Item SLATE_CARPET = register("slate_carpet", new BlockItem(DDBlocks.SLATE_CARPET, new Item.Properties()));
    public static final Item OLIVE_CARPET = register("olive_carpet", new BlockItem(DDBlocks.OLIVE_CARPET, new Item.Properties()));
    public static final Item GOLDEN_CARPET = register("golden_carpet", new BlockItem(DDBlocks.GOLDEN_CARPET, new Item.Properties()));
    public static final Item BEIGE_CARPET = register("beige_carpet", new BlockItem(DDBlocks.BEIGE_CARPET, new Item.Properties()));
    public static final Item TEAL_CARPET = register("teal_carpet", new BlockItem(DDBlocks.TEAL_CARPET, new Item.Properties()));
    public static final Item TURQUOISE_CARPET = register("turquoise_carpet", new BlockItem(DDBlocks.TURQUOISE_CARPET, new Item.Properties()));
    public static final Item AQUA_CARPET = register("aqua_carpet", new BlockItem(DDBlocks.AQUA_CARPET, new Item.Properties()));
    public static final Item VERDANT_CARPET = register("verdant_carpet", new BlockItem(DDBlocks.VERDANT_CARPET, new Item.Properties()));
    public static final Item FOREST_CARPET = register("forest_carpet", new BlockItem(DDBlocks.FOREST_CARPET, new Item.Properties()));
    public static final Item GINGER_CARPET = register("ginger_carpet", new BlockItem(DDBlocks.GINGER_CARPET, new Item.Properties()));
    public static final Item TAN_CARPET = register("tan_carpet", new BlockItem(DDBlocks.TAN_CARPET, new Item.Properties()));

    public static final Item SCARLET_TERRACOTTA = register("scarlet_terracotta", new BlockItem(DDBlocks.SCARLET_TERRACOTTA, new Item.Properties()));
    public static final Item ROSE_TERRACOTTA = register("rose_terracotta", new BlockItem(DDBlocks.ROSE_TERRACOTTA, new Item.Properties()));
    public static final Item CORAL_TERRACOTTA = register("coral_terracotta", new BlockItem(DDBlocks.CORAL_TERRACOTTA, new Item.Properties()));
    public static final Item ROYAL_TERRACOTTA = register("royal_terracotta", new BlockItem(DDBlocks.ROYAL_TERRACOTTA, new Item.Properties()));
    public static final Item PHTHALO_TERRACOTTA = register("phthalo_terracotta", new BlockItem(DDBlocks.PHTHALO_TERRACOTTA, new Item.Properties()));
    public static final Item SLATE_TERRACOTTA = register("slate_terracotta", new BlockItem(DDBlocks.SLATE_TERRACOTTA, new Item.Properties()));
    public static final Item OLIVE_TERRACOTTA = register("olive_terracotta", new BlockItem(DDBlocks.OLIVE_TERRACOTTA, new Item.Properties()));
    public static final Item GOLDEN_TERRACOTTA = register("golden_terracotta", new BlockItem(DDBlocks.GOLDEN_TERRACOTTA, new Item.Properties()));
    public static final Item BEIGE_TERRACOTTA = register("beige_terracotta", new BlockItem(DDBlocks.BEIGE_TERRACOTTA, new Item.Properties()));
    public static final Item TEAL_TERRACOTTA = register("teal_terracotta", new BlockItem(DDBlocks.TEAL_TERRACOTTA, new Item.Properties()));
    public static final Item TURQUOISE_TERRACOTTA = register("turquoise_terracotta", new BlockItem(DDBlocks.TURQUOISE_TERRACOTTA, new Item.Properties()));
    public static final Item AQUA_TERRACOTTA = register("aqua_terracotta", new BlockItem(DDBlocks.AQUA_TERRACOTTA, new Item.Properties()));
    public static final Item VERDANT_TERRACOTTA = register("verdant_terracotta", new BlockItem(DDBlocks.VERDANT_TERRACOTTA, new Item.Properties()));
    public static final Item FOREST_TERRACOTTA = register("forest_terracotta", new BlockItem(DDBlocks.FOREST_TERRACOTTA, new Item.Properties()));
    public static final Item GINGER_TERRACOTTA = register("ginger_terracotta", new BlockItem(DDBlocks.GINGER_TERRACOTTA, new Item.Properties()));
    public static final Item TAN_TERRACOTTA = register("tan_terracotta", new BlockItem(DDBlocks.TAN_TERRACOTTA, new Item.Properties()));

    public static final Item SCARLET_CONCRETE = register("scarlet_concrete", new BlockItem(DDBlocks.SCARLET_CONCRETE, new Item.Properties()));
    public static final Item ROSE_CONCRETE = register("rose_concrete", new BlockItem(DDBlocks.ROSE_CONCRETE, new Item.Properties()));
    public static final Item CORAL_CONCRETE = register("coral_concrete", new BlockItem(DDBlocks.CORAL_CONCRETE, new Item.Properties()));
    public static final Item ROYAL_CONCRETE = register("royal_concrete", new BlockItem(DDBlocks.ROYAL_CONCRETE, new Item.Properties()));
    public static final Item PHTHALO_CONCRETE = register("phthalo_concrete", new BlockItem(DDBlocks.PHTHALO_CONCRETE, new Item.Properties()));
    public static final Item SLATE_CONCRETE = register("slate_concrete", new BlockItem(DDBlocks.SLATE_CONCRETE, new Item.Properties()));
    public static final Item OLIVE_CONCRETE = register("olive_concrete", new BlockItem(DDBlocks.OLIVE_CONCRETE, new Item.Properties()));
    public static final Item GOLDEN_CONCRETE = register("golden_concrete", new BlockItem(DDBlocks.GOLDEN_CONCRETE, new Item.Properties()));
    public static final Item BEIGE_CONCRETE = register("beige_concrete", new BlockItem(DDBlocks.BEIGE_CONCRETE, new Item.Properties()));
    public static final Item TEAL_CONCRETE = register("teal_concrete", new BlockItem(DDBlocks.TEAL_CONCRETE, new Item.Properties()));
    public static final Item TURQUOISE_CONCRETE = register("turquoise_concrete", new BlockItem(DDBlocks.TURQUOISE_CONCRETE, new Item.Properties()));
    public static final Item AQUA_CONCRETE = register("aqua_concrete", new BlockItem(DDBlocks.AQUA_CONCRETE, new Item.Properties()));
    public static final Item VERDANT_CONCRETE = register("verdant_concrete", new BlockItem(DDBlocks.VERDANT_CONCRETE, new Item.Properties()));
    public static final Item FOREST_CONCRETE = register("forest_concrete", new BlockItem(DDBlocks.FOREST_CONCRETE, new Item.Properties()));
    public static final Item GINGER_CONCRETE = register("ginger_concrete", new BlockItem(DDBlocks.GINGER_CONCRETE, new Item.Properties()));
    public static final Item TAN_CONCRETE = register("tan_concrete", new BlockItem(DDBlocks.TAN_CONCRETE, new Item.Properties()));

    public static final Item SCARLET_CONCRETE_POWDER = register("scarlet_concrete_powder", new BlockItem(DDBlocks.SCARLET_CONCRETE_POWDER, new Item.Properties()));
    public static final Item ROSE_CONCRETE_POWDER = register("rose_concrete_powder", new BlockItem(DDBlocks.ROSE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item CORAL_CONCRETE_POWDER = register("coral_concrete_powder", new BlockItem(DDBlocks.CORAL_CONCRETE_POWDER, new Item.Properties()));
    public static final Item ROYAL_CONCRETE_POWDER = register("royal_concrete_powder", new BlockItem(DDBlocks.ROYAL_CONCRETE_POWDER, new Item.Properties()));
    public static final Item PHTHALO_CONCRETE_POWDER = register("phthalo_concrete_powder", new BlockItem(DDBlocks.PHTHALO_CONCRETE_POWDER, new Item.Properties()));
    public static final Item SLATE_CONCRETE_POWDER = register("slate_concrete_powder", new BlockItem(DDBlocks.SLATE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item OLIVE_CONCRETE_POWDER = register("olive_concrete_powder", new BlockItem(DDBlocks.OLIVE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item GOLDEN_CONCRETE_POWDER = register("golden_concrete_powder", new BlockItem(DDBlocks.GOLDEN_CONCRETE_POWDER, new Item.Properties()));
    public static final Item BEIGE_CONCRETE_POWDER = register("beige_concrete_powder", new BlockItem(DDBlocks.BEIGE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item TEAL_CONCRETE_POWDER = register("teal_concrete_powder", new BlockItem(DDBlocks.TEAL_CONCRETE_POWDER, new Item.Properties()));
    public static final Item TURQUOISE_CONCRETE_POWDER = register("turquoise_concrete_powder", new BlockItem(DDBlocks.TURQUOISE_CONCRETE_POWDER, new Item.Properties()));
    public static final Item AQUA_CONCRETE_POWDER = register("aqua_concrete_powder", new BlockItem(DDBlocks.AQUA_CONCRETE_POWDER, new Item.Properties()));
    public static final Item VERDANT_CONCRETE_POWDER = register("verdant_concrete_powder", new BlockItem(DDBlocks.VERDANT_CONCRETE_POWDER, new Item.Properties()));
    public static final Item FOREST_CONCRETE_POWDER = register("forest_concrete_powder", new BlockItem(DDBlocks.FOREST_CONCRETE_POWDER, new Item.Properties()));
    public static final Item GINGER_CONCRETE_POWDER = register("ginger_concrete_powder", new BlockItem(DDBlocks.GINGER_CONCRETE_POWDER, new Item.Properties()));
    public static final Item TAN_CONCRETE_POWDER = register("tan_concrete_powder", new BlockItem(DDBlocks.TAN_CONCRETE_POWDER, new Item.Properties()));

    public static final Item SCARLET_GLAZED_TERRACOTTA = register("scarlet_glazed_terracotta", new BlockItem(DDBlocks.SCARLET_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item ROSE_GLAZED_TERRACOTTA = register("rose_glazed_terracotta", new BlockItem(DDBlocks.ROSE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item CORAL_GLAZED_TERRACOTTA = register("coral_glazed_terracotta", new BlockItem(DDBlocks.CORAL_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item ROYAL_GLAZED_TERRACOTTA = register("royal_glazed_terracotta", new BlockItem(DDBlocks.ROYAL_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item PHTHALO_GLAZED_TERRACOTTA = register("phthalo_glazed_terracotta", new BlockItem(DDBlocks.PHTHALO_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item SLATE_GLAZED_TERRACOTTA = register("slate_glazed_terracotta", new BlockItem(DDBlocks.SLATE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item OLIVE_GLAZED_TERRACOTTA = register("olive_glazed_terracotta", new BlockItem(DDBlocks.OLIVE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item GOLDEN_GLAZED_TERRACOTTA = register("golden_glazed_terracotta", new BlockItem(DDBlocks.GOLDEN_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item BEIGE_GLAZED_TERRACOTTA = register("beige_glazed_terracotta", new BlockItem(DDBlocks.BEIGE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item TEAL_GLAZED_TERRACOTTA = register("teal_glazed_terracotta", new BlockItem(DDBlocks.TEAL_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item TURQUOISE_GLAZED_TERRACOTTA = register("turquoise_glazed_terracotta", new BlockItem(DDBlocks.TURQUOISE_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item AQUA_GLAZED_TERRACOTTA = register("aqua_glazed_terracotta", new BlockItem(DDBlocks.AQUA_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item VERDANT_GLAZED_TERRACOTTA = register("verdant_glazed_terracotta", new BlockItem(DDBlocks.VERDANT_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item FOREST_GLAZED_TERRACOTTA = register("forest_glazed_terracotta", new BlockItem(DDBlocks.FOREST_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item GINGER_GLAZED_TERRACOTTA = register("ginger_glazed_terracotta", new BlockItem(DDBlocks.GINGER_GLAZED_TERRACOTTA, new Item.Properties()));
    public static final Item TAN_GLAZED_TERRACOTTA = register("tan_glazed_terracotta", new BlockItem(DDBlocks.TAN_GLAZED_TERRACOTTA, new Item.Properties()));

    public static final Item SCARLET_STAINED_GLASS = register("scarlet_stained_glass", new BlockItem(DDBlocks.SCARLET_STAINED_GLASS, new Item.Properties()));
    public static final Item ROSE_STAINED_GLASS = register("rose_stained_glass", new BlockItem(DDBlocks.ROSE_STAINED_GLASS, new Item.Properties()));
    public static final Item CORAL_STAINED_GLASS = register("coral_stained_glass", new BlockItem(DDBlocks.CORAL_STAINED_GLASS, new Item.Properties()));
    public static final Item ROYAL_STAINED_GLASS = register("royal_stained_glass", new BlockItem(DDBlocks.ROYAL_STAINED_GLASS, new Item.Properties()));
    public static final Item PHTHALO_STAINED_GLASS = register("phthalo_stained_glass", new BlockItem(DDBlocks.PHTHALO_STAINED_GLASS, new Item.Properties()));
    public static final Item SLATE_STAINED_GLASS = register("slate_stained_glass", new BlockItem(DDBlocks.SLATE_STAINED_GLASS, new Item.Properties()));
    public static final Item OLIVE_STAINED_GLASS = register("olive_stained_glass", new BlockItem(DDBlocks.OLIVE_STAINED_GLASS, new Item.Properties()));
    public static final Item GOLDEN_STAINED_GLASS = register("golden_stained_glass", new BlockItem(DDBlocks.GOLDEN_STAINED_GLASS, new Item.Properties()));
    public static final Item BEIGE_STAINED_GLASS = register("beige_stained_glass", new BlockItem(DDBlocks.BEIGE_STAINED_GLASS, new Item.Properties()));
    public static final Item TEAL_STAINED_GLASS = register("teal_stained_glass", new BlockItem(DDBlocks.TEAL_STAINED_GLASS, new Item.Properties()));
    public static final Item TURQUOISE_STAINED_GLASS = register("turquoise_stained_glass", new BlockItem(DDBlocks.TURQUOISE_STAINED_GLASS, new Item.Properties()));
    public static final Item AQUA_STAINED_GLASS = register("aqua_stained_glass", new BlockItem(DDBlocks.AQUA_STAINED_GLASS, new Item.Properties()));
    public static final Item VERDANT_STAINED_GLASS = register("verdant_stained_glass", new BlockItem(DDBlocks.VERDANT_STAINED_GLASS, new Item.Properties()));
    public static final Item FOREST_STAINED_GLASS = register("forest_stained_glass", new BlockItem(DDBlocks.FOREST_STAINED_GLASS, new Item.Properties()));
    public static final Item GINGER_STAINED_GLASS = register("ginger_stained_glass", new BlockItem(DDBlocks.GINGER_STAINED_GLASS, new Item.Properties()));
    public static final Item TAN_STAINED_GLASS = register("tan_stained_glass", new BlockItem(DDBlocks.TAN_STAINED_GLASS, new Item.Properties()));

    public static final Item SCARLET_STAINED_GLASS_PANE = register("scarlet_stained_glass_pane", new BlockItem(DDBlocks.SCARLET_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item ROSE_STAINED_GLASS_PANE = register("rose_stained_glass_pane", new BlockItem(DDBlocks.ROSE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item CORAL_STAINED_GLASS_PANE = register("coral_stained_glass_pane", new BlockItem(DDBlocks.CORAL_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item ROYAL_STAINED_GLASS_PANE = register("royal_stained_glass_pane", new BlockItem(DDBlocks.ROYAL_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item PHTHALO_STAINED_GLASS_PANE = register("phthalo_stained_glass_pane", new BlockItem(DDBlocks.PHTHALO_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item SLATE_STAINED_GLASS_PANE = register("slate_stained_glass_pane", new BlockItem(DDBlocks.SLATE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item OLIVE_STAINED_GLASS_PANE = register("olive_stained_glass_pane", new BlockItem(DDBlocks.OLIVE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item GOLDEN_STAINED_GLASS_PANE = register("golden_stained_glass_pane", new BlockItem(DDBlocks.GOLDEN_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item BEIGE_STAINED_GLASS_PANE = register("beige_stained_glass_pane", new BlockItem(DDBlocks.BEIGE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item TEAL_STAINED_GLASS_PANE = register("teal_stained_glass_pane", new BlockItem(DDBlocks.TEAL_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item TURQUOISE_STAINED_GLASS_PANE = register("turquoise_stained_glass_pane", new BlockItem(DDBlocks.TURQUOISE_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item AQUA_STAINED_GLASS_PANE = register("aqua_stained_glass_pane", new BlockItem(DDBlocks.AQUA_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item VERDANT_STAINED_GLASS_PANE = register("verdant_stained_glass_pane", new BlockItem(DDBlocks.VERDANT_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item FOREST_STAINED_GLASS_PANE = register("forest_stained_glass_pane", new BlockItem(DDBlocks.FOREST_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item GINGER_STAINED_GLASS_PANE = register("ginger_stained_glass_pane", new BlockItem(DDBlocks.GINGER_STAINED_GLASS_PANE, new Item.Properties()));
    public static final Item TAN_STAINED_GLASS_PANE = register("tan_stained_glass_pane", new BlockItem(DDBlocks.TAN_STAINED_GLASS_PANE, new Item.Properties()));

    public static final Item SCARLET_SHULKER_BOX = register("scarlet_shulker_box", new BlockItem(DDBlocks.SCARLET_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item ROSE_SHULKER_BOX = register("rose_shulker_box", new BlockItem(DDBlocks.ROSE_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item CORAL_SHULKER_BOX = register("coral_shulker_box", new BlockItem(DDBlocks.CORAL_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item ROYAL_SHULKER_BOX = register("royal_shulker_box", new BlockItem(DDBlocks.ROYAL_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item PHTHALO_SHULKER_BOX = register("phthalo_shulker_box", new BlockItem(DDBlocks.PHTHALO_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item SLATE_SHULKER_BOX = register("slate_shulker_box", new BlockItem(DDBlocks.SLATE_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item OLIVE_SHULKER_BOX = register("olive_shulker_box", new BlockItem(DDBlocks.OLIVE_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item GOLDEN_SHULKER_BOX = register("golden_shulker_box", new BlockItem(DDBlocks.GOLDEN_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item BEIGE_SHULKER_BOX = register("beige_shulker_box", new BlockItem(DDBlocks.BEIGE_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item TEAL_SHULKER_BOX = register("teal_shulker_box", new BlockItem(DDBlocks.TEAL_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item TURQUOISE_SHULKER_BOX = register("turquoise_shulker_box", new BlockItem(DDBlocks.TURQUOISE_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item AQUA_SHULKER_BOX = register("aqua_shulker_box", new BlockItem(DDBlocks.AQUA_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item VERDANT_SHULKER_BOX = register("verdant_shulker_box", new BlockItem(DDBlocks.VERDANT_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item FOREST_SHULKER_BOX = register("forest_shulker_box", new BlockItem(DDBlocks.FOREST_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item GINGER_SHULKER_BOX = register("ginger_shulker_box", new BlockItem(DDBlocks.GINGER_SHULKER_BOX, new Item.Properties().stacksTo(1)));
    public static final Item TAN_SHULKER_BOX = register("tan_shulker_box", new BlockItem(DDBlocks.TAN_SHULKER_BOX, new Item.Properties().stacksTo(1)));

    public static final Item SCARLET_CANDLE = register("scarlet_candle", new BlockItem(DDBlocks.SCARLET_CANDLE, new Item.Properties()));
    public static final Item ROSE_CANDLE = register("rose_candle", new BlockItem(DDBlocks.ROSE_CANDLE, new Item.Properties()));
    public static final Item CORAL_CANDLE = register("coral_candle", new BlockItem(DDBlocks.CORAL_CANDLE, new Item.Properties()));
    public static final Item ROYAL_CANDLE = register("royal_candle", new BlockItem(DDBlocks.ROYAL_CANDLE, new Item.Properties()));
    public static final Item PHTHALO_CANDLE = register("phthalo_candle", new BlockItem(DDBlocks.PHTHALO_CANDLE, new Item.Properties()));
    public static final Item SLATE_CANDLE = register("slate_candle", new BlockItem(DDBlocks.SLATE_CANDLE, new Item.Properties()));
    public static final Item OLIVE_CANDLE = register("olive_candle", new BlockItem(DDBlocks.OLIVE_CANDLE, new Item.Properties()));
    public static final Item GOLDEN_CANDLE = register("golden_candle", new BlockItem(DDBlocks.GOLDEN_CANDLE, new Item.Properties()));
    public static final Item BEIGE_CANDLE = register("beige_candle", new BlockItem(DDBlocks.BEIGE_CANDLE, new Item.Properties()));
    public static final Item TEAL_CANDLE = register("teal_candle", new BlockItem(DDBlocks.TEAL_CANDLE, new Item.Properties()));
    public static final Item TURQUOISE_CANDLE = register("turquoise_candle", new BlockItem(DDBlocks.TURQUOISE_CANDLE, new Item.Properties()));
    public static final Item AQUA_CANDLE = register("aqua_candle", new BlockItem(DDBlocks.AQUA_CANDLE, new Item.Properties()));
    public static final Item VERDANT_CANDLE = register("verdant_candle", new BlockItem(DDBlocks.VERDANT_CANDLE, new Item.Properties()));
    public static final Item FOREST_CANDLE = register("forest_candle", new BlockItem(DDBlocks.FOREST_CANDLE, new Item.Properties()));
    public static final Item GINGER_CANDLE = register("ginger_candle", new BlockItem(DDBlocks.GINGER_CANDLE, new Item.Properties()));
    public static final Item TAN_CANDLE = register("tan_candle", new BlockItem(DDBlocks.TAN_CANDLE, new Item.Properties()));

    public static final Item SCARLET_BANNER = register("scarlet_banner", new BannerItem(DDBlocks.SCARLET_BANNER,DDBlocks.SCARLET_WALL_BANNER, new Item.Properties()));
    public static final Item ROSE_BANNER = register("rose_banner", new BannerItem(DDBlocks.ROSE_BANNER,DDBlocks.ROSE_WALL_BANNER, new Item.Properties()));
    public static final Item CORAL_BANNER = register("coral_banner", new BannerItem(DDBlocks.CORAL_BANNER,DDBlocks.CORAL_WALL_BANNER, new Item.Properties()));
    public static final Item ROYAL_BANNER = register("royal_banner", new BannerItem(DDBlocks.ROYAL_BANNER,DDBlocks.ROYAL_WALL_BANNER, new Item.Properties()));
    public static final Item PHTHALO_BANNER = register("phthalo_banner", new BannerItem(DDBlocks.PHTHALO_BANNER,DDBlocks.PHTHALO_WALL_BANNER, new Item.Properties()));
    public static final Item SLATE_BANNER = register("slate_banner", new BannerItem(DDBlocks.SLATE_BANNER,DDBlocks.SLATE_WALL_BANNER, new Item.Properties()));
    public static final Item OLIVE_BANNER = register("olive_banner", new BannerItem(DDBlocks.OLIVE_BANNER,DDBlocks.OLIVE_WALL_BANNER, new Item.Properties()));
    public static final Item GOLDEN_BANNER = register("golden_banner", new BannerItem(DDBlocks.GOLDEN_BANNER,DDBlocks.GOLDEN_WALL_BANNER, new Item.Properties()));
    public static final Item BEIGE_BANNER = register("beige_banner", new BannerItem(DDBlocks.BEIGE_BANNER,DDBlocks.BEIGE_WALL_BANNER, new Item.Properties()));
    public static final Item TEAL_BANNER = register("teal_banner", new BannerItem(DDBlocks.TEAL_BANNER,DDBlocks.TEAL_WALL_BANNER, new Item.Properties()));
    public static final Item TURQUOISE_BANNER = register("turquoise_banner", new BannerItem(DDBlocks.TURQUOISE_BANNER,DDBlocks.TURQUOISE_WALL_BANNER, new Item.Properties()));
    public static final Item AQUA_BANNER = register("aqua_banner", new BannerItem(DDBlocks.AQUA_BANNER,DDBlocks.AQUA_WALL_BANNER, new Item.Properties()));
    public static final Item VERDANT_BANNER = register("verdant_banner", new BannerItem(DDBlocks.VERDANT_BANNER,DDBlocks.VERDANT_WALL_BANNER, new Item.Properties()));
    public static final Item FOREST_BANNER = register("forest_banner", new BannerItem(DDBlocks.FOREST_BANNER,DDBlocks.FOREST_WALL_BANNER, new Item.Properties()));
    public static final Item GINGER_BANNER = register("ginger_banner", new BannerItem(DDBlocks.GINGER_BANNER,DDBlocks.GINGER_WALL_BANNER, new Item.Properties()));
    public static final Item TAN_BANNER = register("tan_banner", new BannerItem(DDBlocks.TAN_BANNER,DDBlocks.TAN_WALL_BANNER, new Item.Properties()));

    public static final Item SCARLET_BED = register("scarlet_bed", new BedItem(DDBlocks.SCARLET_BED, new Item.Properties().stacksTo(1)));
    public static final Item ROSE_BED = register("rose_bed", new BedItem(DDBlocks.ROSE_BED, new Item.Properties().stacksTo(1)));
    public static final Item CORAL_BED = register("coral_bed", new BedItem(DDBlocks.CORAL_BED, new Item.Properties().stacksTo(1)));
    public static final Item ROYAL_BED = register("royal_bed", new BedItem(DDBlocks.ROYAL_BED, new Item.Properties().stacksTo(1)));
    public static final Item PHTHALO_BED = register("phthalo_bed", new BedItem(DDBlocks.PHTHALO_BED, new Item.Properties().stacksTo(1)));
    public static final Item SLATE_BED = register("slate_bed", new BedItem(DDBlocks.SLATE_BED, new Item.Properties().stacksTo(1)));
    public static final Item OLIVE_BED = register("olive_bed", new BedItem(DDBlocks.OLIVE_BED, new Item.Properties().stacksTo(1)));
    public static final Item GOLDEN_BED = register("golden_bed", new BedItem(DDBlocks.GOLDEN_BED, new Item.Properties().stacksTo(1)));
    public static final Item BEIGE_BED = register("beige_bed", new BedItem(DDBlocks.BEIGE_BED, new Item.Properties().stacksTo(1)));
    public static final Item TEAL_BED = register("teal_bed", new BedItem(DDBlocks.TEAL_BED, new Item.Properties().stacksTo(1)));
    public static final Item TURQUOISE_BED = register("turquoise_bed", new BedItem(DDBlocks.TURQUOISE_BED, new Item.Properties().stacksTo(1)));
    public static final Item AQUA_BED = register("aqua_bed", new BedItem(DDBlocks.AQUA_BED, new Item.Properties().stacksTo(1)));
    public static final Item VERDANT_BED = register("verdant_bed", new BedItem(DDBlocks.VERDANT_BED, new Item.Properties().stacksTo(1)));
    public static final Item FOREST_BED = register("forest_bed", new BedItem(DDBlocks.FOREST_BED, new Item.Properties().stacksTo(1)));
    public static final Item GINGER_BED = register("ginger_bed", new BedItem(DDBlocks.GINGER_BED, new Item.Properties().stacksTo(1)));
    public static final Item TAN_BED = register("tan_bed", new BedItem(DDBlocks.TAN_BED, new Item.Properties().stacksTo(1)));

    public static final Item SCARLET_DYE_BASKET = register("scarlet_dye_basket", new BlockItem(DDBlocks.SCARLET_DYE_BASKET, new Item.Properties()));
    public static final Item ROSE_DYE_BASKET = register("rose_dye_basket", new BlockItem(DDBlocks.ROSE_DYE_BASKET, new Item.Properties()));
    public static final Item CORAL_DYE_BASKET = register("coral_dye_basket", new BlockItem(DDBlocks.CORAL_DYE_BASKET, new Item.Properties()));
    public static final Item ROYAL_DYE_BASKET = register("royal_dye_basket", new BlockItem(DDBlocks.ROYAL_DYE_BASKET, new Item.Properties()));
    public static final Item PHTHALO_DYE_BASKET = register("phthalo_dye_basket", new BlockItem(DDBlocks.PHTHALO_DYE_BASKET, new Item.Properties()));
    public static final Item SLATE_DYE_BASKET = register("slate_dye_basket", new BlockItem(DDBlocks.SLATE_DYE_BASKET, new Item.Properties()));
    public static final Item OLIVE_DYE_BASKET = register("olive_dye_basket", new BlockItem(DDBlocks.OLIVE_DYE_BASKET, new Item.Properties()));
    public static final Item GOLDEN_DYE_BASKET = register("golden_dye_basket", new BlockItem(DDBlocks.GOLDEN_DYE_BASKET, new Item.Properties()));
    public static final Item BEIGE_DYE_BASKET = register("beige_dye_basket", new BlockItem(DDBlocks.BEIGE_DYE_BASKET, new Item.Properties()));
    public static final Item TEAL_DYE_BASKET = register("teal_dye_basket", new BlockItem(DDBlocks.TEAL_DYE_BASKET, new Item.Properties()));
    public static final Item TURQUOISE_DYE_BASKET = register("turquoise_dye_basket", new BlockItem(DDBlocks.TURQUOISE_DYE_BASKET, new Item.Properties()));
    public static final Item AQUA_DYE_BASKET = register("aqua_dye_basket", new BlockItem(DDBlocks.AQUA_DYE_BASKET, new Item.Properties()));
    public static final Item VERDANT_DYE_BASKET = register("verdant_dye_basket", new BlockItem(DDBlocks.VERDANT_DYE_BASKET, new Item.Properties()));
    public static final Item FOREST_DYE_BASKET = register("forest_dye_basket", new BlockItem(DDBlocks.FOREST_DYE_BASKET, new Item.Properties()));
    public static final Item GINGER_DYE_BASKET = register("ginger_dye_basket", new BlockItem(DDBlocks.GINGER_DYE_BASKET, new Item.Properties()));
    public static final Item TAN_DYE_BASKET = register("tan_dye_basket", new BlockItem(DDBlocks.TAN_DYE_BASKET, new Item.Properties()));
    public static final Item WHITE_DYE_BASKET = register("white_dye_basket", new BlockItem(DDBlocks.WHITE_DYE_BASKET, new Item.Properties()));
    public static final Item LIGHT_GRAY_DYE_BASKET = register("light_gray_dye_basket", new BlockItem(DDBlocks.LIGHT_GRAY_DYE_BASKET, new Item.Properties()));
    public static final Item GRAY_DYE_BASKET = register("gray_dye_basket", new BlockItem(DDBlocks.GRAY_DYE_BASKET, new Item.Properties()));
    public static final Item BLACK_DYE_BASKET = register("black_dye_basket", new BlockItem(DDBlocks.BLACK_DYE_BASKET, new Item.Properties()));
    public static final Item BROWN_DYE_BASKET = register("brown_dye_basket", new BlockItem(DDBlocks.BROWN_DYE_BASKET, new Item.Properties()));
    public static final Item RED_DYE_BASKET = register("red_dye_basket", new BlockItem(DDBlocks.RED_DYE_BASKET, new Item.Properties()));
    public static final Item ORANGE_DYE_BASKET = register("orange_dye_basket", new BlockItem(DDBlocks.ORANGE_DYE_BASKET, new Item.Properties()));
    public static final Item YELLOW_DYE_BASKET = register("yellow_dye_basket", new BlockItem(DDBlocks.YELLOW_DYE_BASKET, new Item.Properties()));
    public static final Item LIME_DYE_BASKET = register("lime_dye_basket", new BlockItem(DDBlocks.LIME_DYE_BASKET, new Item.Properties()));
    public static final Item CYAN_DYE_BASKET = register("cyan_dye_basket", new BlockItem(DDBlocks.CYAN_DYE_BASKET, new Item.Properties()));
    public static final Item GREEN_DYE_BASKET = register("green_dye_basket", new BlockItem(DDBlocks.GREEN_DYE_BASKET, new Item.Properties()));
    public static final Item BLUE_DYE_BASKET = register("blue_dye_basket", new BlockItem(DDBlocks.BLUE_DYE_BASKET, new Item.Properties()));
    public static final Item LIGHT_BLUE_DYE_BASKET = register("light_blue_dye_basket", new BlockItem(DDBlocks.LIGHT_BLUE_DYE_BASKET, new Item.Properties()));
    public static final Item PURPLE_DYE_BASKET = register("purple_dye_basket", new BlockItem(DDBlocks.PURPLE_DYE_BASKET, new Item.Properties()));
    public static final Item MAGENTA_DYE_BASKET = register("magenta_dye_basket", new BlockItem(DDBlocks.MAGENTA_DYE_BASKET, new Item.Properties()));
    public static final Item PINK_DYE_BASKET = register("pink_dye_basket", new BlockItem(DDBlocks.PINK_DYE_BASKET, new Item.Properties()));
    
    private static Item register(String id, Item item) {
        return Registry.register(BuiltInRegistries.ITEM, new ResourceLocation(DyeDepot.MOD_ID, id), item);
    }
}
